/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rsicarelli.kplatform

import com.rsicarelli.kplatform.options.AndroidAppOptionsBuilder
import com.rsicarelli.kplatform.options.AndroidLibraryOptionsBuilder
import org.gradle.api.Plugin
import org.gradle.api.Project

class KplatformPlugin : Plugin<Project> {

    override fun apply(project: Project) = Unit
}

fun Project.androidApp(builderAction: AndroidAppOptionsBuilder.() -> Unit = { }) = applyAndroidApp(
    AndroidAppOptionsBuilder().apply(builderAction).build()
)

fun Project.androidLibrary(builderAction: AndroidLibraryOptionsBuilder.() -> Unit = { }) = applyAndroidLibrary(
    AndroidLibraryOptionsBuilder().apply(builderAction).build()
)

fun Project.jvmLibrary() = applyJvmLibrary()
