/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rsicarelli.kplatform

import org.gradle.api.Plugin
import org.gradle.api.Project

class KplatformPlugin : Plugin<Project> {

    override fun apply(project: Project) = Unit
}

fun Project.androidApp() = applyAndroidApp()
