/*
 * Copyright (c) Rodrigo Sicarelli 2023.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rsicarelli

import org.gradle.api.Plugin
import org.gradle.api.Project

class KPlatformPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin KPlatform plugin")
            }
        }
    }
}
