/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rsicarelli.buildlogic

import org.gradle.api.Plugin
import org.gradle.api.Project

class BuildLogicPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'build.logic.greeting'")
            }
        }
    }
}
